### ISSUE TITLE
[bug] validazione risultato tornei

### ISSUE THREAD

**Issue by tipodue** [ZorziG/Manzo_works#3]
```
cosa scegli? 9
1) nome: Jund, formato: Modern, prezzo: 3
2) nome: Blue Moon, formato: Modern, prezzo: 1
---
mazzo da scegliere:1
nome: Jund, formato: Modern, prezzo: 3
---
inserisci il nome del torneo: FNM Agosto
Inserire win-lose-tie:
Posizione finale del torneo: 
Traceback (most recent call last):
  File "Manzo.py", line 391, in <module>
    elabora_scelta_utente(scelta)
  File "Manzo.py", line 377, in elabora_scelta_utente
    tournament_result(deck)
  File "Manzo.py", line 313, in tournament_result
    file.write(f"{tournament['tournament_name']}"
IndexError: string index out of range
```

esplode

**Comment by ZorziG** [comment]
fixato
